import {
  Boxes,
  GaugeIcon,
  GemIcon,
  SearchIcon,
  Ticket,
  PieChartIcon,
  NotepadTextIcon,
  AlignLeftIcon,
  PlaneTakeoffIcon,
  HotelIcon,
  BusIcon,
  UsersIcon,
  LockKeyholeIcon,
  UnplugIcon,
  CogIcon,
  LayoutListIcon,
} from "lucide-react";
export const AppIcons = {
  dashboard: <GaugeIcon />,
  search: <SearchIcon />,
  ticket: <Ticket />,
  boxes: <Boxes />,
  priceLine: <GemIcon />,
  report: <NotepadTextIcon />,
  control: <CogIcon />,
  menu: <AlignLeftIcon />,
  pieChart: <PieChartIcon />,
  plane: <PlaneTakeoffIcon />,
  hotel: <HotelIcon />,
  bus: <BusIcon />,
  users: <UsersIcon />,
  lockOpen: <LockKeyholeIcon />,
  unplug: <UnplugIcon />,
  layoutList: <LayoutListIcon />,
};
